# Site Info
title:              "protolife"
description:        "Rezowanul Haque's Personal Blog"
# google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-22521139-4 # Put your Google Analytics code

# Author Info
author_name:        "Rezowanul Haque" # Your name here
author_email:       hnrird@gmail.com # Your email here
author_gravatar:    826fef6a1e871191c46ffbb8e7d23c18 # Your Gravatar md5 hash here for logo
# twitter_username:   HeiswayiNrird # Your Twitter username here
github_username:    ntrezowan # Your GitHub username here

# Site Settings
# baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
baseurl:            null
permalink:          /notes/:title # Post permalink
timezone:           America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap
  - jekyll-seo-tag



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
